apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  labels:
    app: ecommerce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ecommerce
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ecommerce
    spec:
      containers:
        - name: app
          image: vstorozhenko/ecommerce-app:1.0
          args:
            - bash
            - -c
            - alembic upgrade head && python ecommerce/main.py
          ports:
            - containerPort: 8000
          resources: {}
          volumeMounts:
            - name: app-volume
              mountPath: /app/ecommerce
      restartPolicy: Always
      volumes:
        - name: app-volume
          hostPath:
            path: /Users/vstorozhenko/PycharmProjects/FastApiProject/ecommerce
