apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    db: postgres
spec:
  type: LoadBalancer
  ports:
    - name: "5432"
      port: 5432
      targetPort: 5432
  selector:
    db: postgres
