apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  labels:
    app: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  strategy: Recreate
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - image: redis:7
          name: redis
          ports:
            - containerPort: 6379
          resources: {}
      restartPolicy: Always
