"""empty message

Revision ID: 5f351c0f930d
Revises: bf228e0fa983
Create Date: 2022-05-06 13:34:39.749460

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f351c0f930d'
down_revision = 'bf228e0fa983'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # op.create_table('categories',
    # sa.Column('id', sa.Integer(), nullable=False),
    # sa.Column('name', sa.String(length=50), nullable=True),
    # sa.PrimaryKeyConstraint('id')
    # )
    # op.create_table('users',
    # sa.Column('id', sa.Integer(), nullable=False),
    # sa.Column('name', sa.String(), nullable=True),
    # sa.Column('password', sa.String(), nullable=True),
    # sa.Column('email', sa.String(), nullable=True),
    # sa.PrimaryKeyConstraint('id'),
    # sa.UniqueConstraint('email')
    # )
    # op.create_table('carts',
    # sa.Column('id', sa.Integer(), nullable=False),
    # sa.Column('created_date', sa.DateTime(), nullable=True),
    # sa.Column('user_id', sa.Integer(), nullable=True),
    # sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    # sa.PrimaryKeyConstraint('id')
    # )
    # op.create_table('products',
    # sa.Column('id', sa.Integer(), nullable=False),
    # sa.Column('name', sa.String(length=50), nullable=True),
    # sa.Column('description', sa.String(length=200), nullable=True),
    # sa.Column('quantity', sa.Integer(), nullable=True),
    # sa.Column('price', sa.Float(), nullable=True),
    # sa.Column('category_id', sa.Integer(), nullable=True),
    # sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='CASCADE'),
    # sa.PrimaryKeyConstraint('id')
    # )
    # op.create_table('cart_items',
    # sa.Column('id', sa.Integer(), nullable=False),
    # sa.Column('created_date', sa.DateTime(), nullable=True),
    # sa.Column('cart_id', sa.Integer(), nullable=True),
    # sa.Column('product_id', sa.Integer(), nullable=True),
    # sa.ForeignKeyConstraint(['cart_id'], ['carts.id'], ondelete='CASCADE'),
    # sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    # sa.PrimaryKeyConstraint('id')
    # )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cart_items')
    op.drop_table('products')
    op.drop_table('carts')
    op.drop_table('users')
    op.drop_table('categories')
    # ### end Alembic commands ###
