"""empty message

Revision ID: 8b32975e4c8e
Revises: 9f5b9939ed37
Create Date: 2022-05-05 20:38:52.672226

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b32975e4c8e'
down_revision = '9f5b9939ed37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # op.add_column('products', sa.Column('category_id', sa.Integer(), nullable=True))
    # op.create_foreign_key(None, 'products', 'category', ['category_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_column('products', 'category_id')
    # ### end Alembic commands ###
